// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/age.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Birthdate     string                 `protobuf:"bytes,1,opt,name=birthdate,proto3" json:"birthdate,omitempty"` // Format: "YYYY-MM-DD"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgeRequest) Reset() {
	*x = AgeRequest{}
	mi := &file_proto_age_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgeRequest) ProtoMessage() {}

func (x *AgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_age_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgeRequest.ProtoReflect.Descriptor instead.
func (*AgeRequest) Descriptor() ([]byte, []int) {
	return file_proto_age_proto_rawDescGZIP(), []int{0}
}

func (x *AgeRequest) GetBirthdate() string {
	if x != nil {
		return x.Birthdate
	}
	return ""
}

type AgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Age           int32                  `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	IsAdult       bool                   `protobuf:"varint,2,opt,name=is_adult,json=isAdult,proto3" json:"is_adult,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgeResponse) Reset() {
	*x = AgeResponse{}
	mi := &file_proto_age_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgeResponse) ProtoMessage() {}

func (x *AgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_age_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgeResponse.ProtoReflect.Descriptor instead.
func (*AgeResponse) Descriptor() ([]byte, []int) {
	return file_proto_age_proto_rawDescGZIP(), []int{1}
}

func (x *AgeResponse) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *AgeResponse) GetIsAdult() bool {
	if x != nil {
		return x.IsAdult
	}
	return false
}

type AverageAgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Age           int32                  `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AverageAgeRequest) Reset() {
	*x = AverageAgeRequest{}
	mi := &file_proto_age_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AverageAgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AverageAgeRequest) ProtoMessage() {}

func (x *AverageAgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_age_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AverageAgeRequest.ProtoReflect.Descriptor instead.
func (*AverageAgeRequest) Descriptor() ([]byte, []int) {
	return file_proto_age_proto_rawDescGZIP(), []int{2}
}

func (x *AverageAgeRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type AverageAgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Average       float64                `protobuf:"fixed64,1,opt,name=average,proto3" json:"average,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AverageAgeResponse) Reset() {
	*x = AverageAgeResponse{}
	mi := &file_proto_age_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AverageAgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AverageAgeResponse) ProtoMessage() {}

func (x *AverageAgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_age_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AverageAgeResponse.ProtoReflect.Descriptor instead.
func (*AverageAgeResponse) Descriptor() ([]byte, []int) {
	return file_proto_age_proto_rawDescGZIP(), []int{3}
}

func (x *AverageAgeResponse) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

var File_proto_age_proto protoreflect.FileDescriptor

const file_proto_age_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/age.proto\x12\x03age\"*\n" +
	"\n" +
	"AgeRequest\x12\x1c\n" +
	"\tbirthdate\x18\x01 \x01(\tR\tbirthdate\":\n" +
	"\vAgeResponse\x12\x10\n" +
	"\x03age\x18\x01 \x01(\x05R\x03age\x12\x19\n" +
	"\bis_adult\x18\x02 \x01(\bR\aisAdult\"%\n" +
	"\x11AverageAgeRequest\x12\x10\n" +
	"\x03age\x18\x01 \x01(\x05R\x03age\".\n" +
	"\x12AverageAgeResponse\x12\x18\n" +
	"\aaverage\x18\x01 \x01(\x01R\aaverage2\x81\x01\n" +
	"\n" +
	"AgeService\x12+\n" +
	"\x06GetAge\x12\x0f.age.AgeRequest\x1a\x10.age.AgeResponse\x12F\n" +
	"\x11ComputeAverageAge\x12\x16.age.AverageAgeRequest\x1a\x17.age.AverageAgeResponse(\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_proto_age_proto_rawDescOnce sync.Once
	file_proto_age_proto_rawDescData []byte
)

func file_proto_age_proto_rawDescGZIP() []byte {
	file_proto_age_proto_rawDescOnce.Do(func() {
		file_proto_age_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_age_proto_rawDesc), len(file_proto_age_proto_rawDesc)))
	})
	return file_proto_age_proto_rawDescData
}

var file_proto_age_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_age_proto_goTypes = []any{
	(*AgeRequest)(nil),         // 0: age.AgeRequest
	(*AgeResponse)(nil),        // 1: age.AgeResponse
	(*AverageAgeRequest)(nil),  // 2: age.AverageAgeRequest
	(*AverageAgeResponse)(nil), // 3: age.AverageAgeResponse
}
var file_proto_age_proto_depIdxs = []int32{
	0, // 0: age.AgeService.GetAge:input_type -> age.AgeRequest
	2, // 1: age.AgeService.ComputeAverageAge:input_type -> age.AverageAgeRequest
	1, // 2: age.AgeService.GetAge:output_type -> age.AgeResponse
	3, // 3: age.AgeService.ComputeAverageAge:output_type -> age.AverageAgeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_age_proto_init() }
func file_proto_age_proto_init() {
	if File_proto_age_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_age_proto_rawDesc), len(file_proto_age_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_age_proto_goTypes,
		DependencyIndexes: file_proto_age_proto_depIdxs,
		MessageInfos:      file_proto_age_proto_msgTypes,
	}.Build()
	File_proto_age_proto = out.File
	file_proto_age_proto_goTypes = nil
	file_proto_age_proto_depIdxs = nil
}
