// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/age.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgeService_GetAge_FullMethodName            = "/age.AgeService/GetAge"
	AgeService_ComputeAverageAge_FullMethodName = "/age.AgeService/ComputeAverageAge"
)

// AgeServiceClient is the client API for AgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgeServiceClient interface {
	GetAge(ctx context.Context, in *AgeRequest, opts ...grpc.CallOption) (*AgeResponse, error)
	ComputeAverageAge(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AverageAgeRequest, AverageAgeResponse], error)
}

type ageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgeServiceClient(cc grpc.ClientConnInterface) AgeServiceClient {
	return &ageServiceClient{cc}
}

func (c *ageServiceClient) GetAge(ctx context.Context, in *AgeRequest, opts ...grpc.CallOption) (*AgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgeResponse)
	err := c.cc.Invoke(ctx, AgeService_GetAge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ageServiceClient) ComputeAverageAge(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AverageAgeRequest, AverageAgeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgeService_ServiceDesc.Streams[0], AgeService_ComputeAverageAge_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AverageAgeRequest, AverageAgeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgeService_ComputeAverageAgeClient = grpc.ClientStreamingClient[AverageAgeRequest, AverageAgeResponse]

// AgeServiceServer is the server API for AgeService service.
// All implementations must embed UnimplementedAgeServiceServer
// for forward compatibility.
type AgeServiceServer interface {
	GetAge(context.Context, *AgeRequest) (*AgeResponse, error)
	ComputeAverageAge(grpc.ClientStreamingServer[AverageAgeRequest, AverageAgeResponse]) error
	mustEmbedUnimplementedAgeServiceServer()
}

// UnimplementedAgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgeServiceServer struct{}

func (UnimplementedAgeServiceServer) GetAge(context.Context, *AgeRequest) (*AgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAge not implemented")
}
func (UnimplementedAgeServiceServer) ComputeAverageAge(grpc.ClientStreamingServer[AverageAgeRequest, AverageAgeResponse]) error {
	return status.Error(codes.Unimplemented, "method ComputeAverageAge not implemented")
}
func (UnimplementedAgeServiceServer) mustEmbedUnimplementedAgeServiceServer() {}
func (UnimplementedAgeServiceServer) testEmbeddedByValue()                    {}

// UnsafeAgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgeServiceServer will
// result in compilation errors.
type UnsafeAgeServiceServer interface {
	mustEmbedUnimplementedAgeServiceServer()
}

func RegisterAgeServiceServer(s grpc.ServiceRegistrar, srv AgeServiceServer) {
	// If the following call panics, it indicates UnimplementedAgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgeService_ServiceDesc, srv)
}

func _AgeService_GetAge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgeServiceServer).GetAge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgeService_GetAge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgeServiceServer).GetAge(ctx, req.(*AgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgeService_ComputeAverageAge_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgeServiceServer).ComputeAverageAge(&grpc.GenericServerStream[AverageAgeRequest, AverageAgeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgeService_ComputeAverageAgeServer = grpc.ClientStreamingServer[AverageAgeRequest, AverageAgeResponse]

// AgeService_ServiceDesc is the grpc.ServiceDesc for AgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "age.AgeService",
	HandlerType: (*AgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAge",
			Handler:    _AgeService_GetAge_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ComputeAverageAge",
			Handler:       _AgeService_ComputeAverageAge_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/age.proto",
}
