// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/fibonacci.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FibonacciRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int32                  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FibonacciRequest) Reset() {
	*x = FibonacciRequest{}
	mi := &file_proto_fibonacci_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FibonacciRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibonacciRequest) ProtoMessage() {}

func (x *FibonacciRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fibonacci_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibonacciRequest.ProtoReflect.Descriptor instead.
func (*FibonacciRequest) Descriptor() ([]byte, []int) {
	return file_proto_fibonacci_proto_rawDescGZIP(), []int{0}
}

func (x *FibonacciRequest) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

type FibonacciResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FibonacciResponse) Reset() {
	*x = FibonacciResponse{}
	mi := &file_proto_fibonacci_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FibonacciResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibonacciResponse) ProtoMessage() {}

func (x *FibonacciResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fibonacci_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibonacciResponse.ProtoReflect.Descriptor instead.
func (*FibonacciResponse) Descriptor() ([]byte, []int) {
	return file_proto_fibonacci_proto_rawDescGZIP(), []int{1}
}

func (x *FibonacciResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_proto_fibonacci_proto protoreflect.FileDescriptor

const file_proto_fibonacci_proto_rawDesc = "" +
	"\n" +
	"\x15proto/fibonacci.proto\x12\tfibonacci\" \n" +
	"\x10FibonacciRequest\x12\f\n" +
	"\x01n\x18\x01 \x01(\x05R\x01n\")\n" +
	"\x11FibonacciResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value2_\n" +
	"\x10FibonacciService\x12K\n" +
	"\fGetFibonacci\x12\x1b.fibonacci.FibonacciRequest\x1a\x1c.fibonacci.FibonacciResponse0\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_proto_fibonacci_proto_rawDescOnce sync.Once
	file_proto_fibonacci_proto_rawDescData []byte
)

func file_proto_fibonacci_proto_rawDescGZIP() []byte {
	file_proto_fibonacci_proto_rawDescOnce.Do(func() {
		file_proto_fibonacci_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fibonacci_proto_rawDesc), len(file_proto_fibonacci_proto_rawDesc)))
	})
	return file_proto_fibonacci_proto_rawDescData
}

var file_proto_fibonacci_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_fibonacci_proto_goTypes = []any{
	(*FibonacciRequest)(nil),  // 0: fibonacci.FibonacciRequest
	(*FibonacciResponse)(nil), // 1: fibonacci.FibonacciResponse
}
var file_proto_fibonacci_proto_depIdxs = []int32{
	0, // 0: fibonacci.FibonacciService.GetFibonacci:input_type -> fibonacci.FibonacciRequest
	1, // 1: fibonacci.FibonacciService.GetFibonacci:output_type -> fibonacci.FibonacciResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_fibonacci_proto_init() }
func file_proto_fibonacci_proto_init() {
	if File_proto_fibonacci_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fibonacci_proto_rawDesc), len(file_proto_fibonacci_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fibonacci_proto_goTypes,
		DependencyIndexes: file_proto_fibonacci_proto_depIdxs,
		MessageInfos:      file_proto_fibonacci_proto_msgTypes,
	}.Build()
	File_proto_fibonacci_proto = out.File
	file_proto_fibonacci_proto_goTypes = nil
	file_proto_fibonacci_proto_depIdxs = nil
}
