// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/slow.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SlowService_ProcessSlow_FullMethodName = "/slow.SlowService/ProcessSlow"
)

// SlowServiceClient is the client API for SlowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SlowServiceClient interface {
	ProcessSlow(ctx context.Context, in *SlowRequest, opts ...grpc.CallOption) (*SlowResponse, error)
}

type slowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSlowServiceClient(cc grpc.ClientConnInterface) SlowServiceClient {
	return &slowServiceClient{cc}
}

func (c *slowServiceClient) ProcessSlow(ctx context.Context, in *SlowRequest, opts ...grpc.CallOption) (*SlowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SlowResponse)
	err := c.cc.Invoke(ctx, SlowService_ProcessSlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SlowServiceServer is the server API for SlowService service.
// All implementations must embed UnimplementedSlowServiceServer
// for forward compatibility.
type SlowServiceServer interface {
	ProcessSlow(context.Context, *SlowRequest) (*SlowResponse, error)
	mustEmbedUnimplementedSlowServiceServer()
}

// UnimplementedSlowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSlowServiceServer struct{}

func (UnimplementedSlowServiceServer) ProcessSlow(context.Context, *SlowRequest) (*SlowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessSlow not implemented")
}
func (UnimplementedSlowServiceServer) mustEmbedUnimplementedSlowServiceServer() {}
func (UnimplementedSlowServiceServer) testEmbeddedByValue()                     {}

// UnsafeSlowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SlowServiceServer will
// result in compilation errors.
type UnsafeSlowServiceServer interface {
	mustEmbedUnimplementedSlowServiceServer()
}

func RegisterSlowServiceServer(s grpc.ServiceRegistrar, srv SlowServiceServer) {
	// If the following call panics, it indicates UnimplementedSlowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SlowService_ServiceDesc, srv)
}

func _SlowService_ProcessSlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlowServiceServer).ProcessSlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SlowService_ProcessSlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlowServiceServer).ProcessSlow(ctx, req.(*SlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SlowService_ServiceDesc is the grpc.ServiceDesc for SlowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SlowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "slow.SlowService",
	HandlerType: (*SlowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessSlow",
			Handler:    _SlowService_ProcessSlow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/slow.proto",
}
